FROM golang:1.9.1 as usersvc

RUN go get github.com/golang/dep && go install github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/baddayduck/services/usersvc
COPY usersvc .
WORKDIR /go/src/github.com/baddayduck/services/usersvc/cmd/usersvc
RUN dep ensure -vendor-only  
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o usersvc .

FROM alpine
COPY --from=usersvc /go/src/github.com/baddayduck/services/usersvc/cmd/usersvc /bin
ENTRYPOINT [ "/bin/usersvc" ] 
