FROM golang:1.9.1 as usersvc_build

RUN go get github.com/golang/dep && go install github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/baddayduck/services/usersvc
COPY usersvc .
RUN dep ensure -vendor-only  
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o usersvc .

FROM alpine:3.6 
COPY --from=usersvc_build /go/src/github.com/baddayduck/services/usersvc/cmd/usersvc/usersvc /bin
ENTRYPOINT [ "/bin/usersvc" ] 
